services:
  postgres:
    image: postgres:18
    container_name: cav-postgres

    environment:
      POSTGRES_DB: cav_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - cav-postgres-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d cav_db"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build: .
    container_name: cav-backend-container

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cav_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy


  frontend:
    build:
      context: ../../cav-frontend
      args:
        VITE_API_BASE_URL: http://localhost:8080

    container_name: cav-frontend-container

    ports:
      - "5173:80"

    depends_on:
      - backend


volumes:
  cav-postgres-data:
    external: true
    name: cav-postgres-data