# Production Database Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Swagger / OpenAPI disabled in production
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Disable Open Session in View
spring.jpa.open-in-view=false