# Development Database Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Swagger / OpenAPI enabled in development
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Disable Open Session in View
spring.jpa.open-in-view=false

logging.level.com.example.cav_backend=DEBUG