CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',

    CONSTRAINT uk_app_user_username
        UNIQUE (username)
);

CREATE TABLE esim_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eid VARCHAR(64) NOT NULL,
    iccid VARCHAR(32) NOT NULL,
    operator VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,

    CONSTRAINT uk_esim_profile_iccid
        UNIQUE (iccid),

    CONSTRAINT esim_profile_operator_check
        CHECK (
            operator IN (
                'TURKCELL',
                'VODAFONE',
                'TURK_TELEKOM'
            )
        ),

    CONSTRAINT esim_profile_status_check
        CHECK (
            status IN (
                'CREATED',
                'DOWNLOADING',
                'DOWNLOADED',
                'ENABLED',
                'FAILED'
            )
        )
);