ALTER TABLE esim_profile
ADD COLUMN created_at TIMESTAMP WITH TIME ZONE
NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE esim_profile
ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE
NOT NULL DEFAULT CURRENT_TIMESTAMP;